### ISSUE TITLE
Latest version update

### ISSUE THREAD

**Issue by kubukoz** [scala-ts/scala-ts#2487]
**Describe the bug/feature request**

The latest version on GitHub appears as 0.4.0, from 2017, which may deter people from using the library. If you go to tags instead, you'll find 0.7.0 from August 2024. I suggest that a release from the **0.7.0 tag** is made and marked as latest to improve its visibility.

In addition, the docs suggest using 0.5.19:

```
addSbtPlugin("io.github.scala-ts" % "sbt-scala-ts" % "0.5.19")
```

This should be updated, and improved so that this version is in sync with the latest.

Thanks for the library, I'm investigating using it in a project :)

**Comment by cchantep** [comment]
Hi,

Tag is not used for the release process of this repository.
Latest artifacts version is indicated on the [README](https://github.com/scala-ts/scala-ts?tab=readme-ov-file#scala-ts) badge, in the [release notes](https://scala-ts.github.io/scala-ts/release-notes.html) or on Maven Search.

**Comment by kubukoz** [comment]
I understand, I just think it would improve the potential user's experience :)

this looks counterintuitive, to say the least:

<img width="273" alt="image" src="https://github.com/user-attachments/assets/57663074-9fd2-4913-9cb6-c10995f75e56">

**Comment by raquo** [comment]
@cchantep I'll bring up this issue again...

I almost didn't recommend this project to someone who needed it because I thought that it was abandoned for the exact same reason – last release showing 0.4.0 nine years ago.

Yes, technically, you have the badges showing the real current version, but they're tiny and way down there below the fold; and above all else I don't expect github UI to show outright incorrect information about when the last release happened. By default I trust the information it's showing me, so I stopped searching for the latest version after I saw the latest release being "0.4.0".

I suggest two easy steps to eliminate the confusion:
1. delete all 0.1.0 ... 0.4.0 "releases" from github so that they don't confuse people with "last release 9 years ago", and
2. prominently link to the release notes from the readme.

**Comment by cchantep** [comment]
Hi,

Thanks for bringing this up again. The old releases are removed.

The latest release is already indicated at the top of the README. The release notes are also at the top of the online documentation, which is linked at the top of the README and from the repository.
